CREATE TYPE rsvp_options AS ENUM ('Will attend', 'Regetfully decline', 'Not yet responded');


CREATE TYPE age AS ENUM ('Adult', 'Child');


CREATE TABLE invites (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                                                     family_name TEXT NOT NULL,
                                                                                      head_of_house TEXT NOT NULL,
                                                                                                         keyword TEXT NOT NULL);


CREATE TABLE people (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                                                    family_id INTEGER REFERENCES invites(id) NOT NULL,
                                                                                                             last_name TEXT NOT NULL,
                                                                                                                            first_name TEXT NOT NULL,
                                                                                                                                            rsvp rsvp_options NOT NULL,
                                                                                                                                                              person_age age NOT NULL,
                                                                                                                                                                             allowed_extra BOOLEAN, extra_confirmed rsvp_options)